
# source director
FREERTOS_SRC_DIR     = $(FREERTOS_DIR)
FREERTOS_INC_DIR     = $(FREERTOS_DIR)/include
FREERTOS_ARM_CM4_DIR = $(FREERTOS_DIR)/portable/GCC/ARM_CM4F
FREERTOS_MemMang_DIR = $(FREERTOS_DIR)/portable/MemMang
FREERTOS_CMSIS_RTOS_DIR = $(FREERTOS_DIR)/CMSIS_RTOS

# add freertos source
SRC  += $(FREERTOS_SRC_DIR)/list.c
SRC  += $(FREERTOS_SRC_DIR)/queue.c
SRC  += $(FREERTOS_SRC_DIR)/croutine.c
SRC  += $(FREERTOS_SRC_DIR)/event_groups.c
SRC  += $(FREERTOS_SRC_DIR)/tasks.c
SRC  += $(FREERTOS_SRC_DIR)/timers.c

SRC  += $(FREERTOS_ARM_CM4_DIR)/port.c

SRC  += $(FREERTOS_MemMang_DIR)/heap_4.c
SRC  += $(FREERTOS_CMSIS_RTOS_DIR)/cmsis_os.c

# include directories
INCLUDE_DIRS += $(FREERTOS_INC_DIR)
INCLUDE_DIRS += $(FREERTOS_ARM_CM4_DIR)
INCLUDE_DIRS += $(FREERTOS_CMSIS_RTOS_DIR)


