    /* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "FreeRTOS.h"
#include "cmsis_os.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_Run1(void);
extern void test_systime(void);

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}

/*=======MAIN=====*/
int UnityTestMain(void)
{
    printf( "\n\n======== UnityTest V1.0 (%s,%s) ========\n\n", __DATE__, __TIME__ );
    UnityBegin("UnityTest/TestProductionCode.c");
    RUN_TEST(test_Run1, 1);
    RUN_TEST(test_systime, 2);

  return (UnityEnd());
}

void unity_Test_Task( void const* argument )
{
    UnityTestMain();

    do
    {
        osDelay(5000);
    }while(1);
}